baseURL = "https://knowyourscientist.github.io/"
languageCode = "en-us"
title = "Know Your Scientist"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true

# Site Params
[params]
logo = "images/logo.png"

# meta data
author = "Know Your Scientist"
description = "This is meta description"

home = "Home"
logo = "images/logo.png"
menufixed = false

[Languages.en]
weight = 2
languageCode = "en-us"
title = "Example site multi-language"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/logo.png"
menufixed = false

footerDescription = "Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "About"
footerSubscribeTitle = "Subscribe"


# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "Know Your Scientist"
description = "Know Your Scientist Punline or short discription"
button  = true
btnText = "Know More"
btnURL  = "https://themefisher.com/"
#videoThumb = "images/slider/video-player-thumb.jpg"
#videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "we want to connect wtih the community and share our passion for science"
description = "some more description"

# Blog Section On Homepage
[Languages.en.params.blog]
enable  = true
#topTitle= ""
title   = "Blog."
subtitle= "Know about our upcomming and past events."

# Contact Section
[Languages.en.params.contact]
enable  = true
topTitle= "DROP US A NOTE"
title   = "Contact Us."
email = "gettoknowyourscientist@gmail.com"
subtitle= "We would love to hear from you."
#address = "14/05, Stockhome <br> Victori Palace , United States"
#phone   = "(03) 9283 2617"
#fax     = "+61 3827 3590"
#facebook= "https://www.facebook.com/"
#twitter = "https://twitter.com/"
#linkedin= "https://www.linkedin.com/"
#dribbble= "https://dribbble.com/"
#instagram= "https://www.instagram.com/"
#mapLatitude = "51.507351"
#mapLongitude= "-0.127758"
#mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Let's Create Something Together"
subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "blog"
url     = "blog"
weight  = 3
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 4

